name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  docker_build_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: KAnggara/DevOps/dockerbuild@latest
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
