name: LateX CV to PDF

on:
  push:
    branches: 
      - main
      - dev
    tags:
       - '*'
  pull_request:
    branches: [ main ]

jobs:
  tex_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile test LaTeX document with Maths
        id: math-docs
        uses: ./
        with:
          output_dir: output
          main_latex_file: test/test.tex
          ctan_packages: amsmath amsfonts lua-uni-algos
      - name: Upload PDF to the workflow tab
        id: upload-math-docs
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output/test.pdf

      - name: Compile LaTeX document with fontawesome
        id: fontawesome-docs
        uses: ./
        with:
          output_dir: output
          main_latex_file: test/test-fontawesome.tex
          ctan_packages: moderncv colortbl fontawesome lua-uni-algos

      - name: Upload PDF to the workflow tab
        id: upload-fontawesome-docs
        uses: actions/upload-artifact@v4
        with:
          name: output-fontawesome
          path: output/test-fontawesome.pdf

      - name: Compile LaTeX document with TOC
        id: toc-docs
        uses: ./
        with:
          output_dir: output
          main_latex_file: test/test-toc.tex
          ctan_packages: lua-uni-algos
          toc: true
      - name: Upload PDF to the workflow tab
        id: upload-toc-docs
        uses: actions/upload-artifact@v4
        with:
          name: output-toc
          path: output/test-toc.pdf